spring.application.name=auth-service

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=srinu

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true