# ===============================
# SERVER
# ===============================
server.port=8081
spring.application.name=auth-service

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=srinu

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT
# ===============================
jwt.secret=my-super-secret-key-12345678901234567890
jwt.expiration=86400000

# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joshimalavika6@gmail.com
spring.mail.password=oyacvlcvghygssav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CONSUL
# ===============================
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.prefer-ip-address=false
spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}

# HEALTH CHECK (IMPORTANT)
spring.cloud.consul.discovery.register-health-check=true
spring.cloud.consul.discovery.health-check-path=/actuator/health

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.mail.enabled=false

# IMPORTANT FOR SERVICE TYPE
spring.main.web-application-type=servlet