spring.application.name=customerManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/plans_db
spring.datasource.username=postgres
spring.datasource.password=1823

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
customer.service.base-url=http://localhost:8082
customer.service.income-endpoint=/customers/1/35000