<<<<<<< HEAD
server.port=8082

spring.application.name=customer-service

spring.datasource.url=jdbc:postgresql://localhost:5432/plans_db
=======
spring.application.name=customerManagemet

server.port = 8082
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_management_db
>>>>>>> bae531b (Updated customer module and removed .idea files)
spring.datasource.username=postgres
spring.datasource.password=1823

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
customer.service.base-url=http://localhost:8082
customer.service.income-endpoint=/customers/1/35000

# JWT
jwt.secret=my-super-secret-key-12345678901234567890
jwt.expiration=86400000

<<<<<<< HEAD

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonydivya2001@gmail.com
spring.mail.password=xtmixxuqvorpxuls
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
=======
>>>>>>> bae531b (Updated customer module and removed .idea files)
