# ===============================
# SERVER CONFIG
# ===============================
server.port=8082

# ===============================
# APPLICATION NAME
# ===============================
spring.application.name=customer-service

# ===============================
# DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/dfs_db
spring.datasource.username=postgres
spring.datasource.password=srinu
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EMAIL CONFIG (OTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srinulucky7660@gmail.com
spring.mail.password=yuitbncqmpgzwubi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CONSUL CONFIG
# ===============================
spring.cloud.consul.discovery.enabled=true

# ===============================
# LOGGING (OPTIONAL)
# ===============================
logging.level.org.springframework=INFO
logging.level.com.dfs.customer=DEBUG

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.prefer-ip-address=false