server.port=8085

spring.application.name=fund-service

spring.datasource.url=jdbc:postgresql://localhost:5432/funddb
spring.datasource.username=postgres
spring.datasource.password=srinu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consul
spring.cloud.consul.discovery.enabled=true

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500


spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.prefer-ip-address=false

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.cloud.consul.discovery.health-check-path=/actuator/health