# ===============================
# SERVER
# ===============================
server.port=9999
spring.application.name=api-gateway

# ===============================
# CONSUL
# ===============================
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.prefer-ip-address=false
spring.cloud.consul.discovery.hostname=localhost

# ===============================
# LOAD BALANCER
# ===============================
spring.cloud.discovery.enabled=true
spring.cloud.loadbalancer.enabled=true


# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# VERY IMPORTANT (gateway health check)
spring.cloud.consul.discovery.health-check-path=/actuator/health

# ===============================
# ROUTES (ALL SERVICES - FIXED)
# ===============================

# AUTH
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# CUSTOMER AUTH
spring.cloud.gateway.server.webflux.routes[1].id=customer-auth
spring.cloud.gateway.server.webflux.routes[1].uri=lb://auth-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/customer/**

# LOAN SERVICE
spring.cloud.gateway.server.webflux.routes[2].id=loan-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://loan-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/loans/**

# CUSTOMER SERVICE
spring.cloud.gateway.server.webflux.routes[3].id=customer-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://customer-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/customers/**

# PAYMENT SERVICE
spring.cloud.gateway.server.webflux.routes[4].id=payment-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/payments/**

# PLAN SERVICE
spring.cloud.gateway.server.webflux.routes[5].id=plan-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://plan-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/plans/**

# FUND SERVICE
spring.cloud.gateway.server.webflux.routes[6].id=fund-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://fund-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/fund/**

# TRANSACTION SERVICE
spring.cloud.gateway.server.webflux.routes[7].id=transaction-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://transaction-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/transactions/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=StripPrefix=1



