server.port=9999
spring.application.name=api-gateway

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true

spring.cloud.consul.discovery.hostname=localhost
spring.cloud.consul.discovery.prefer-ip-address=false


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ================= AUTH =================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ================= CUSTOMER AUTH =================
spring.cloud.gateway.routes[1].id=customer-auth
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customer/**

spring.cloud.gateway.routes[2].id=loan-service
spring.cloud.gateway.routes[2].uri=lb://loan-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/loans/**

spring.cloud.gateway.routes[3].id=customer-service
spring.cloud.gateway.routes[3].uri=lb://customer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/customers/**

# ================= PAYMENT SERVICE =================
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**



# ================= PLAN SERVICE =================
spring.cloud.gateway.routes[5].id=plan-service
spring.cloud.gateway.routes[5].uri=lb://plan-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/plans/**

# ================= FUND SERVICE =================
spring.cloud.gateway.routes[6].id=fund-service
spring.cloud.gateway.routes[6].uri=lb://fund-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/fund/**

# ================= TRANSACTION SERVICE =================
spring.cloud.gateway.routes[7].id=transaction-service
spring.cloud.gateway.routes[7].uri=lb://transaction-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/transactions/**
