server.port=9999
spring.application.name=api-gateway

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# ================= AUTH =================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# ================= CUSTOMER AUTH =================
spring.cloud.gateway.routes[1].id=customer-auth
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customer/**


