# Application Name
spring.application.name=payment-service

# Server Port
server.port=8085

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/plans_db
spring.datasource.username=postgres
spring.datasource.password=1823
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONTEXT PATH
# ===============================
server.servlet.context-path=/api/v1

# ===============================
# LOAN SERVICE (for future use)
# ===============================
loan.service.base-url=http://localhost:8080/api/v1/loans


