server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=joshi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

payment.service.base-url=http://localhost:8085/payments
customer.service.base-url=http://localhost:8080/api/v1
fines.service.base-url=http://localhost:8085/fines
guarantor.service.base-url=http://localhost:8080/api/v1/customers
plans.service.base-url=http://localhost:8081
agent.service.base-url=http://localhost:8082/api/agents
loan.service.base-url=http://localhost:8082/api

spring.application.name=TransactionAndReport