
# ===============================
# SERVER CONFIGURATION
# ===============================

server.port=8082
spring.application.name=loanagent-module


# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/loan_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# LOGGING (OPTIONAL BUT USEFUL)
# ===============================

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# EXTERNAL MICROSERVICE URLS
# ===============================

services.customer-service.url=http://localhost:8081/api/v1/customers
services.plan-service.url=http://localhost:8082/api/v1/plans


# ===============================
# CONNECTION POOL (OPTIONAL)
# ===============================

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000


# ===============================
# JACKSON CONFIGURATION
# ===============================

#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=UTC
